# my config
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: ngocqui/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo 'composer install'
            echo 'docker-compose down'
            echo 'docker-compose pull'
            echo 'docker-compose up -d'
  deploy:
    executor: docker/docker
    working_directory: /var/circleci/react
    steps:
      # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
      - add_ssh_keys:
          fingerprints:
            - "57:5b:b5:23:1e:d2:d2:ae:88:ab:d2:08:c1:ba:36:76"
      - run:
          command: |
            ssh -oStrictHostKeyChecking=no jenkins@13.212.79.132 "bash deploy.sh"

workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push
